export const Images = {
  addavatar: require("../assets/images/graphics/add avatar.png"),
  capybaraloading: require("../assets/images/graphics/capybara loading.png"),
  achievement: require("../assets/images/graphics/achievement.png"),
  addition: require("../assets/images/graphics/addition.png"),
  avatarFemale: require("../assets/images/graphics/avatar female.png"),
  avatarMale: require("../assets/images/graphics/avatar male.png"),
  badge: require("../assets/images/graphics/badge.png"),
  capybaraAndBird: require("../assets/images/graphics/capybara and bird.png"),
  capybaraHoldingChicken: require("../assets/images/graphics/capybara holding chicken thigh.png"),
  capybaraHoldingHeart: require("../assets/images/graphics/capybara holding heart.png"),
  capybaraHoldingOilLamp: require("../assets/images/graphics/capybara holding oil lamp.png"),
  capybaraHoldingSandwich: require("../assets/images/graphics/capybara holding sandwich.png"),
  capybaraSoccer: require("../assets/images/graphics/capybara soccer.png"),
  contact: require("../assets/images/graphics/contact.png"),
  dark: require("../assets/images/graphics/dark.png"),
  div: require("../assets/images/graphics/div.png"),
  division: require("../assets/images/graphics/division.png"),
  eight: require("../assets/images/graphics/eight.png"),
  english: require("../assets/images/graphics/english.png"),
  equalMark: require("../assets/images/graphics/equal mark.png"),
  exercise: require("../assets/images/graphics/exercise.png"),
  five: require("../assets/images/graphics/five.png"),
  four: require("../assets/images/graphics/four.png"),
  game: require("../assets/images/graphics/game.png"),
  lesson: require("../assets/images/graphics/lesson.png"),
  light: require("../assets/images/graphics/light.png"),
  logoDark: require("../assets/images/graphics/logo dark.png"),
  logoLight: require("../assets/images/graphics/logo light.png"),
  minus: require("../assets/images/graphics/minus.png"),
  multip: require("../assets/images/graphics/multip.png"),
  multiplicationTables: require("../assets/images/graphics/multiplication tables.png"),
  multiplication: require("../assets/images/graphics/multiplication.png"),
  nine: require("../assets/images/graphics/nine.png"),
  notification: require("../assets/images/graphics/notification.png"),
  one: require("../assets/images/graphics/one.png"),
  plus: require("../assets/images/graphics/plus.png"),
  point: require("../assets/images/graphics/point.png"),
  profile: require("../assets/images/graphics/profile.png"),
  progressTest: require("../assets/images/graphics/progress test.png"),
  questionMark: require("../assets/images/graphics/question mark.png"),
  question: require("../assets/images/graphics/question.png"),
  rank: require("../assets/images/graphics/rank.png"),
  reward2: require("../assets/images/graphics/reward (2).png"),
  reward: require("../assets/images/graphics/reward.png"),
  setting: require("../assets/images/graphics/setting.png"),
  seven: require("../assets/images/graphics/seven.png"),
  six: require("../assets/images/graphics/six.png"),
  soundOff: require("../assets/images/graphics/sound off.png"),
  soundOn: require("../assets/images/graphics/sound on.png"),
  subtraction: require("../assets/images/graphics/subtraction.png"),
  target: require("../assets/images/graphics/target.png"),
  testLevel: require("../assets/images/graphics/test level.png"),
  test: require("../assets/images/graphics/test.png"),
  three: require("../assets/images/graphics/three.png"),
  time2: require("../assets/images/graphics/time (2).png"),
  time: require("../assets/images/graphics/time.png"),
  top1: require("../assets/images/graphics/top 1.png"),
  top2: require("../assets/images/graphics/top 2.png"),
  top3: require("../assets/images/graphics/top 3.png"),
  top: require("../assets/images/graphics/top.png"),
  vietnamese: require("../assets/images/graphics/vietnamese.png"),
  zero: require("../assets/images/graphics/zero.png"),
};
