import { StyleSheet } from "react-native";
import { Fonts } from "../../../constants/Fonts";

export default function createStyles(theme) {
  return StyleSheet.create({
    container: {
      flex: 1,
      paddingTop: 20,
    },
    header: {
      borderBottomLeftRadius: 50,
      borderBottomRightRadius: 50,
      padding: 20,
      elevation: 3,
    },
    headerContent: {
      flexDirection: "row",
      justifyContent: "space-between",
      alignItems: "center",
    },
    userRow: {
      flexDirection: "row",
      alignItems: "center",
      gap: 10,
    },
    avatarContainer: {
      marginVertical: 10,
      borderRadius: 50,
      borderWidth: 1,
      borderColor: theme.colors.white,
      backgroundColor: theme.colors.avatartBackground,
      elevation: 3,
    },
    avatar: {
      width: 60,
      height: 60,
      resizeMode: "cover",
      borderRadius: 50,
    },
    greeting: {
      color: theme.colors.white,
      fontSize: 16,
      fontFamily: Fonts.NUNITO_REGULAR,
    },
    name: {
      color: theme.colors.white,
      fontSize: 24,
      fontFamily: Fonts.NUNITO_BOLD,
      width: "80%",
    },
    notificationContainer: {
      position: "relative",
      backgroundColor: theme.colors.cardBackground,
      borderRadius: 50,
      padding: 10,
      elevation: 3,
      borderWidth: 1,
      borderColor: theme.colors.white,
    },
    badge: {
      position: "absolute",
      top: -2,
      right: -2,
      backgroundColor: theme.colors.red,
      width: 18,
      height: 18,
      borderRadius: 9,
      justifyContent: "center",
      alignItems: "center",
      borderWidth: 1,
      borderColor: theme.colors.white,
    },
    badgeText: {
      color: theme.colors.white,
      fontSize: 10,
      fontFamily: Fonts.NUNITO_MEDIUM,
    },
    notificationIcon: {
      width: 30,
      height: 30,
    },
    gradeWrapper: {
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "center",
      paddingHorizontal: 10,
      paddingVertical: 6,
      marginTop: 20,
      marginHorizontal: 20,
      backgroundColor: theme.colors.cardBackground,
      borderRadius: 10,
      // elevation: 5,
    },

    dropdown: {
      position: "absolute",
      top: 175,
      left: 20,
      width: "89%",
      backgroundColor: theme.colors.cardBackground,
      borderRadius: 10,
      // elevation: 3,
      paddingVertical: 5,
    },

    grade: {
      fontSize: 14,
      color: theme.colors.blueDark,
      fontFamily: Fonts.NUNITO_MEDIUM,
    },
    gradeRow: {
      flexDirection: "row",
      alignItems: "center",
      gap: 5,
    },
    periodWrapper: {
      width: "60%",
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "center",
      paddingHorizontal: 20,
      paddingVertical: 6,
      marginTop: 20,
      marginHorizontal: 20,
      backgroundColor: theme.colors.cardBackground,
      borderRadius: 10,
      // elevation: 3,
    },
    dropdownButtonText: {
      fontFamily: Fonts.NUNITO_MEDIUM,
      fontSize: 13,
      color: theme.colors.black,
    },
    dropdownDay: {
      position: "absolute",
      top: 230,
      left: 20,
      width: "60%",
      backgroundColor: theme.colors.cardBackground,
      borderRadius: 5,
      // elevation: 3,
      overflow: "hidden",
    },

    dropdownItem: {
      paddingHorizontal: 15,
      paddingVertical: 3,
      borderBottomColor: theme.colors.grayLight,
      borderBottomWidth: 1,
    },

    dropdownItemText: {
      fontFamily: Fonts.NUNITO_MEDIUM,
      fontSize: 13,
      color: theme.colors.black,
      textAlign: "center",
      // elevation: 20,
    },
    academicChartContainer: {
      marginTop: 80,
      alignItems: "center",
    },
    chartName: {
      color: theme.colors.white,
      fontSize: 22,
      fontFamily: Fonts.NUNITO_MEDIUM,
      marginBottom: 10,
    },
    chartNoteContainer: {
      marginTop: 10,
      flexDirection: "row",
      justifyContent: "center",
      gap: 20,
    },
    chartNote: { flexDirection: "row", alignItems: "center" },
    noteLast: {
      width: 12,
      height: 12,
      backgroundColor: theme.colors.grayLight,
      marginRight: 6,
      borderRadius: 2,
    },
    noteThis: {
      width: 12,
      height: 12,
      backgroundColor: theme.colors.blueDark,
      marginRight: 6,
      borderRadius: 2,
    },
    tfChartContainer: { marginTop: 30, alignItems: "center" },
    noteTrue: {
      width: 12,
      height: 12,
      backgroundColor: theme.colors.green,
      marginRight: 6,
      borderRadius: 2,
    },
    noteFalse: {
      width: 12,
      height: 12,
      backgroundColor: theme.colors.redTomato,
      marginRight: 6,
      borderRadius: 2,
    },
    commentContainer: {
      width: "90%",
      backgroundColor: theme.colors.cardBackground,
      marginHorizontal: 20,
      marginVertical: 20,
      padding: 10,
      borderTopLeftRadius: 20,
      borderBottomRightRadius: 20,
      // elevation: 3,
    },
    commentTitle: {
      fontSize: 16,
      fontFamily: Fonts.NUNITO_MEDIUM,
      color: theme.colors.comment,
    },
    summaryContainer: {
      width: "90%",
      backgroundColor: theme.colors.cardBackground,
      padding: 10,
      borderTopLeftRadius: 20,
      borderBottomRightRadius: 20,
      // elevation: 3,
      marginBottom: 10,
    },
    summaryTitle: {
      fontSize: 16,
      fontFamily: Fonts.NUNITO_MEDIUM,
      color: theme.colors.green,
    },
    commentText: {
      fontSize: 14,
      fontFamily: Fonts.NUNITO_MEDIUM,
      color: theme.colors.black,
    },
    skillName: {
      fontWeight: "bold",
      fontFamily: Fonts.NUNITO_BOLD,
      color: theme.colors.black,
    },
    noteText: {
      fontSize: 12,
      color: theme.colors.black,
      fontFamily: Fonts.NUNITO_MEDIUM,
    },
  });
}
